Print a better error message when missing protoc/proto-lens-protoc.
Example output when `protoc` is missing:

    Configuring proto-lens-protobuf-types-0.2.1.0...
    proto-lens-protobuf-types-0.2.1.0: build (lib)
    ==========
    Error: couldn't find the executable "protoc" in your $PATH.
	Follow the installation instructions at https://google.github.io/proto-lens/installing-protoc.html .
    ==========
    Missing executable "protoc"
    CallStack (from HasCallStack):
    error, called at src/Data/ProtoLens/Setup.hs:296:13 in
    proto-lens-protoc-0.2.1.0-EdtYegZINjJ3cgy3Ej8Sfv:Data.ProtoLens.Setup