Use tasty-hunit fully instead of HUnit.
Previously we switched from `test-framework` to `tasty`,
but continued to use `Test.HUnit` for simple assertion tests.
Unfortunately,  HUnit's exceptions don't get printed nicely by
`tasty`. For example:

```
    bytes:           FAIL
      Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "proto-lens-tests-0.1.0.1-CZ6Ohah6nNGOHV46uMAQt", srcLocModule = "Data.ProtoLens.TestUtil", srcLocFile = "src/Data/ProtoLens/TestUtil.hs", srcLocStartLine = 93, srcLocStartCol = 5, srcLocEndLine = 93, srcLocEndCol = 48})) (ExpectedButGot Nothing "\"a: 151\"" "\"a: 150\"")
```

If we switch completely over to importing functions like `=@?`
from `Test.Tasty.HUnit` instead of `Test.HUnit`, we'll get
nicer exceptions like we did with `test-framework`:

```
    bytes:           FAIL
      src/Data/ProtoLens/TestUtil.hs:92:
      expected: "a: 151"
       but got: "a: 150"
```